name: "Vendorfiles Updater"
description: "Update vendorfiles for a project"
author: "Araxeus"
branding:
  icon: "box"
  color: "yellow"

inputs:
  token:
    description: "github token to circumvent rate limits"
    required: true
  package-manager:
    description: "package manager to use"
    default: ""

runs:
  using: "composite"
  steps:
    - name: Run vendor update
      id: vendor
      run: |
        echo "PR_BODY<<EOF" >> $GITHUB_OUTPUT
        echo "$(${{ inputs.package-manager }} vendor update --pr)" >> $GITHUB_OUTPUT
        echo "EOF" >> $GITHUB_OUTPUT
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.token }}

    - name: Show PR body
      shell: bash
      run: echo '${{ steps.vendor.outputs.PR_BODY}}'

    - name: Show git status
      shell: bash
      run: git status

    - name: Check if PR body starts with "ERROR"
      if: startsWith(steps.vendor.outputs.PR_BODY, 'ERROR:')
      shell: bash
      run: exit 1

    - name: create pull request footer
      id: footer
      shell: bash
      run: |
        echo "PR_FOOTER<<EOF" >> $GITHUB_OUTPUT
        echo -e "\n\n>"'This PR was generated using [vendorfiles](https://www.github.com/Araxeus/vendorfiles)' >> $GITHUB_OUTPUT
        echo "EOF" >> $GITHUB_OUTPUT

    - name: Create Pull Request
      if: steps.vendor.outputs.PR_BODY != 0
      uses: peter-evans/create-pull-request@v5
      with:
        commit-message: "[vendorfiles] Bump vendors"
        committer: "vendorfiles[bot] <vendorfiles[bot]@users.noreply.github.com>"
        author: "vendorfiles[bot] <vendorfiles[bot]@users.noreply.github.com>"
        branch: bump-vendors
        title: "[vendorfiles] Bump vendors"
        body: ${{ steps.vendor.outputs.PR_BODY}}${{ steps.footer.outputs.PR_FOOTER}}
        delete-branch: true
        labels: dependencies
        reviewers: ${{ github.repository_owner }}
        # assignees: ${{ github.repository_owner }}
        token: ${{ inputs.token }}
